import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl uppercase text-center text-gray-800 mt-8">
        We Are Above The System
      </h1>

      {/* Header */}

      {/* Nav */}

      {/* Results */}
    </div>
  );
}
